# Autogenerated Nushell completion script for chezmoi

# Manage your dotfiles across multiple diverse machines, securely
export extern "chezmoi" [
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --help # help for chezmoi
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --version # version for chezmoi
  --working-tree # Set working tree directory
]


# Add an existing file, directory, or symlink to the source state
export extern "chezmoi add" [
  --autotemplate # Generate the template when adding files as templates
  --create # Add files that should exist, irrespective of their contents
  --encrypt # Encrypt files
  --exact # Add directories exactly
  --exclude # Exclude entry types (default none)
  --follow # Add symlink targets instead of symlinks
  --help # help for add
  --include # Include entry types (default all)
  --prompt # Prompt before adding each entry
  --quiet # Suppress warnings
  --recursive # Recurse into subdirectories (default true)
  --secrets # Scan for secrets when adding unencrypted files (default warning)
  --template # Add files as templates
  --template-symlinks # Add symlinks with target in source or home dirs as templates
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Interact with age
export extern "chezmoi age" [
  --help # help for age
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Update the destination directory to match the target state
export extern "chezmoi apply" [
  --exclude # Exclude entry types (default none)
  --help # help for apply
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --parent-dirs # Apply all parent directories
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Generate a tar archive of the target state
export extern "chezmoi archive" [
  --exclude # Exclude entry types (default none)
  --format # Set archive format (default tar.gz)
  --gzip # Compress output with gzip
  --help # help for archive
  --include # Include entry types (default none)
  --init # Recreate config file from template
  --parent-dirs # Archive parent directories
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the target contents of a file, script, or symlink
export extern "chezmoi cat" [
  --help # help for cat
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the configuration file
export extern "chezmoi cat-config" [
  --help # help for cat-config
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Launch a shell in the source directory
export extern "chezmoi cd" [
  --help # help for cd
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Change the attributes of a target in the source state
export extern "chezmoi chattr" [
  --help # help for chattr
  --recursive # Recurse into subdirectories
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Generate shell completion code
export extern "chezmoi completion" [
  --help # help for completion
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the template data
export extern "chezmoi data" [
  --format # Output format
  --help # help for data
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Decrypt file or standard input
export extern "chezmoi decrypt" [
  --help # help for decrypt
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Permanently delete an entry from the source state, the destination directory, and the state
export extern "chezmoi destroy" [
  --help # help for destroy
  --recursive # Recurse into subdirectories
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the diff between the target state and the destination state
export extern "chezmoi diff" [
  --exclude # Exclude entry types (default none)
  --help # help for diff
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --pager # Set pager (default "\x00")
  --parent-dirs # Print the diff of all parent directories
  --recursive # Recurse into subdirectories
  --reverse # Reverse the direction of the diff
  --script-contents # Show script contents (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Check your system for potential problems
export extern "chezmoi doctor" [
  --help # help for doctor
  --no-network # do not use network connection
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Generate a dump of the target state
export extern "chezmoi dump" [
  --exclude # Exclude entry types (default none)
  --format # Output format
  --help # help for dump
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --parent-dirs # Dump all parent directories
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Dump the configuration values
export extern "chezmoi dump-config" [
  --format # Output format
  --help # help for dump-config
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Edit the source state of a target
export extern "chezmoi edit" [
  --apply # Apply after editing
  --exclude # Exclude entry types (default none)
  --hardlink # Invoke editor with a hardlink to the source file (default true)
  --help # help for edit
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --watch # Apply on save
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Edit the configuration file
export extern "chezmoi edit-config" [
  --help # help for edit-config
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Edit the configuration file template
export extern "chezmoi edit-config-template" [
  --help # help for edit-config-template
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Encrypt file or standard input
export extern "chezmoi encrypt" [
  --help # help for encrypt
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Execute the given template(s)
export extern "chezmoi execute-template" [
  --file # Treat arguments as filenames
  --help # help for execute-template
  --init # Simulate chezmoi init
  --left-delimiter # Set left template delimiter
  --promptBool # Simulate promptBool (default [])
  --promptChoice # Simulate promptChoice (default [])
  --promptInt # Simulate promptInt (default [])
  --promptMultichoice # Simulate promptMultichoice (default [])
  --promptString # Simulate promptString (default [])
  --right-delimiter # Set right template delimiter
  --stdinisatty # Simulate stdinIsATTY (default true)
  --with-stdin # Set .chezmoi.stdin to the contents of the standard input
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Remove a target from the source state
export extern "chezmoi forget" [
  --help # help for forget
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Generate a file for use with chezmoi
export extern "chezmoi generate" [
  --help # help for generate
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Run git in the source directory
export extern "chezmoi git" [
  --help # help for git
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print ignored targets
export extern "chezmoi ignored" [
  --help # help for ignored
  --tree # Print paths as a tree
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Import an archive into the source state
export extern "chezmoi import" [
  --destination # Set destination prefix
  --exact # Set exact_ attribute on imported directories
  --exclude # Exclude entry types (default none)
  --help # help for import
  --include # Include entry types (default all)
  --remove-destination # Remove destination before import
  --strip-components # Strip leading path components
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Setup the source directory and update the destination directory to match the target state
export extern "chezmoi init" [
  --apply # Update destination directory
  --branch # Set initial branch to checkout
  --config-path # Path to write generated config file
  --data # Include existing template data (default true)
  --depth # Create a shallow clone
  --exclude # Exclude entry types (default none)
  --git-lfs # Run git pull lfs after cloning
  --guess-repo-url # Guess the repo URL (default true)
  --help # help for init
  --include # Include entry types (default all)
  --one-shot # Run in one-shot mode
  --prompt # Force prompt*Once template functions to prompt
  --promptBool # Populate promptBool (default [])
  --promptChoice # Populate promptChoice (default [])
  --promptDefaults # Make prompt functions return default values
  --promptInt # Populate promptInt (default [])
  --promptMultichoice # Populate promptMultichoice (default [])
  --promptString # Populate promptString (default [])
  --purge # Purge config and source directories after running
  --purge-binary # Purge chezmoi binary after running
  --recurse-submodules # Checkout submodules recursively (default true)
  --ssh # Use ssh instead of https when guessing repo URL
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print license
export extern "chezmoi license" [
  --help # help for license
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# List the managed entries in the destination directory
export extern "chezmoi managed" [
  --exclude # Exclude entry types (default none)
  --format # Format (default json)
  --help # help for managed
  --include # Include entry types (default all)
  --path-style # Path style (default relative)
  --tree # Print paths as a tree
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Perform a three-way merge between the destination state, the source state, and the target state
export extern "chezmoi merge" [
  --help # help for merge
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Perform a three-way merge for each modified file
export extern "chezmoi merge-all" [
  --help # help for merge-all
  --init # Recreate config file from template
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Purge chezmoi's configuration and data
export extern "chezmoi purge" [
  --binary # Purge chezmoi binary
  --help # help for purge
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Re-add modified files
export extern "chezmoi re-add" [
  --exclude # Exclude entry types (default none)
  --help # help for re-add
  --include # Include entry types (default all)
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Interact with a secret manager
export extern "chezmoi secret" [
  --help # help for secret
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the source path of a target
export extern "chezmoi source-path" [
  --help # help for source-path
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Manipulate the persistent state
export extern "chezmoi state" [
  --help # help for state
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Show the status of targets
export extern "chezmoi status" [
  --exclude # Exclude entry types (default none)
  --help # help for status
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --parent-dirs # Show status of all parent directories
  --path-style # Path style (default relative)
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Print the target path of a source path
export extern "chezmoi target-path" [
  --help # help for target-path
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# List the unmanaged files in the destination directory
export extern "chezmoi unmanaged" [
  --help # help for unmanaged
  --path-style # Path style (default relative)
  --tree # Print paths as a tree
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Pull and apply any changes
export extern "chezmoi update" [
  --apply # Apply after pulling (default true)
  --exclude # Exclude entry types (default none)
  --help # help for update
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --parent-dirs # Update all parent directories
  --recurse-submodules # Recursively update submodules (default true)
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Upgrade chezmoi to the latest released version
export extern "chezmoi upgrade" [
  --executable # Set executable to replace
  --help # help for upgrade
  --method # Set upgrade method
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]

# Exit with success if the destination state matches the target state, fail otherwise
export extern "chezmoi verify" [
  --exclude # Exclude entry types (default none)
  --help # help for verify
  --include # Include entry types (default all)
  --init # Recreate config file from template
  --parent-dirs # Verify all parent directories
  --recursive # Recurse into subdirectories (default true)
  --cache # Set cache directory
  --color # Colorize output (default auto)
  --config # Set config file
  --config-format # Set config file format
  --debug # Include debug information in output
  --destination # Set destination directory
  --dry-run # Do not make any modifications to the destination directory
  --force # Make all changes without prompting
  --interactive # Prompt for all changes
  --keep-going # Keep going as far as possible after an error
  --mode # Mode (default file)
  --no-pager # Do not use the pager
  --no-tty # Do not attempt to get a TTY for prompts
  --output # Write output to path instead of stdout
  --persistent-state # Set persistent state file
  --progress # Display progress bars (default auto)
  --refresh-externals # Refresh external cache (default auto)
  --source # Set source directory
  --source-path # Specify targets by source path
  --use-builtin-age # Use builtin age (default auto)
  --use-builtin-diff # Use builtin diff
  --use-builtin-git # Use builtin git (default auto)
  --verbose # Make output more verbose
  --working-tree # Set working tree directory
]
