return {
  -- {
  --   "yetone/avante.nvim",
  --   build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
  --     or "make",
  --   event = "VeryLazy",
  --   version = false, -- Never set this value to "*"! Never!
  --   dependencies = {
  --     "nvim-lua/plenary.nvim",
  --     "MunifTanjim/nui.nvim",
  --     -- optional
  --     "folke/snacks.nvim", -- for input provider snacks
  --     "nvim-tree/nvim-web-devicons", -- or echasnovski/mini.icons
  --     "zbirenbaum/copilot.lua", -- for providers='copilot'
  --     {
  --       -- support for image pasting
  --       "HakonHarnes/img-clip.nvim",
  --       event = "VeryLazy",
  --       opts = {
  --         -- recommended settings
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           -- required for Windows users
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       -- Make sure to set this up properly if you have lazy=true
  --       "MeanderingProgrammer/render-markdown.nvim",
  --       opts = {
  --         file_types = { "markdown", "Avante" },
  --       },
  --       ft = { "markdown", "Avante" },
  --     },
  --   },
  --   keys = {
  --     { "<leader>a", "", desc = "+ai", mode = { "n", "v" } },
  --     -- {
  --     --   "<leader>aa",
  --     --   function()
  --     --     require("avante.api").ask()
  --     --   end,
  --     --   desc = "Ask (Avante)",
  --     --   mode = { "n", "v" },
  --     -- },
  --     -- {
  --     --   "<leader>an",
  --     --   function()
  --     --     require("avante.api").ask({ new_chat = true })
  --     --   end,
  --     --   desc = "New Chat (Avante)",
  --     --   mode = { "n", "v" },
  --     -- },
  --     -- {
  --     --   "<leader>ae",
  --     --   function()
  --     --     require("avante.api").edit()
  --     --   end,
  --     --   desc = "Edit (Avante)",
  --     --   mode = "v",
  --     -- },
  --     -- {
  --     --   "<leader>ae",
  --     --   function()
  --     --     require("avante.api").stop()
  --     --   end,
  --     --   desc = "Stop (Avante)",
  --     --   mode = "n",
  --     -- },
  --     -- {
  --     --   "<leader>ar",
  --     --   function()
  --     --     require("avante.api").refresh()
  --     --   end,
  --     --   desc = "Refresh (Avante)",
  --     --   mode = "n",
  --     -- },
  --     -- {
  --     --   "<leader>af",
  --     --   function()
  --     --     require("avante.api").focus()
  --     --   end,
  --     --   desc = "Focus (Avante)",
  --     --   mode = "n",
  --     -- },
  --     -- {
  --     --   "<leader>at",
  --     --   function()
  --     --     require("avante").toggle()
  --     --   end,
  --     --   desc = "Toggle (Avante)",
  --     --   mode = "n",
  --     -- },
  --     -- {
  --     --   "<leader>aB",
  --     --   function()
  --     --     require("avante.api").add_buffer_files()
  --     --   end,
  --     --   desc = "Add Buffer Files (Avante)",
  --     --   mode = "n",
  --     -- },
  --   },
  --   opts = {
  --     provider = "copilot",
  --     -- providers = {
  --     --   copilot = {
  --     --     model = "claude-sonnet-4",
  --     --   },
  --     -- },
  --     auto_suggestions_provider = "copilot",
  --     windows = {
  --       wrap = false,
  --     },
  --     behaviour = {
  --       -- auto_set_keymaps = false,
  --     },
  --     selector = {
  --       provider = "snacks",
  --     },
  --     input = {
  --       provider = "snacks",
  --     },
  --     file_selector = {
  --       provider = "snacks",
  --     },
  --     use_absolute_path = function() end,
  --   },
  --   config = function(_, opts)
  --     require("avante").setup(opts)
  --
  --     vim.api.nvim_set_hl(0, "AvanteSidebarNormal", { link = "Normal" })
  --     vim.api.nvim_set_hl(0, "AvantePopupHint", { link = "Normal" })
  --     vim.api.nvim_set_hl(0, "AvanteSidebarWinSeparator", { link = "WinSeparator" })
  --     vim.api.nvim_set_hl(0, "AvanteSidebarWinHorizontalSeparator", { link = "WinSeparator" })
  --   end,
  -- },
  -- -- {
  -- --   "yetone/avante.nvim",
  -- --   opts = function()
  -- --     require("snacks")
  -- --       .toggle({
  -- --         name = "Sidebar (Avante)",
  -- --         get = function()
  -- --           return require("avante").is_sidebar_open()
  -- --         end,
  -- --         set = function(state)
  -- --           require("avante").toggle_sidebar({ ask = state })
  -- --         end,
  -- --       })
  -- --       :map("<leader>at")
  -- --   end,
  -- -- },
  -- {
  --   "saghen/blink.cmp",
  --   dependencies = {
  --     "Kaiser-Yang/blink-cmp-avante",
  --   },
  --   opts = {
  --     sources = {
  --       default = { "avante" },
  --       providers = {
  --         avante = {
  --           name = "avante",
  --           module = "blink-cmp-avante",
  --           opts = {
  --             avante = {
  --               command = {
  --                 get_kind_name = function(_)
  --                   return "AvanteCmd"
  --                 end,
  --               },
  --               mention = {
  --                 get_kind_name = function(_)
  --                   return "AvanteMention"
  --                 end,
  --               },
  --               shortcut = {
  --                 get_kind_name = function(_)
  --                   return "AvanteShortcut"
  --                 end,
  --               },
  --             },
  --             kind_icons = {
  --               AvanteCmd = " ",
  --               AvanteMention = " ",
  --               AvanteShortcut = " ",
  --             },
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
