#!/usr/bin/zsh

# function dot {
local -a req_cmds=(bat chezmoi fzf)
for cmd in ${req_cmds[@]}; do
  if (( ! ${+commands[$cmd]} )); then
    print -P "%B%F{red}error%f%b: $cmd not found."
    return 1
  fi
done

local -a files timestamps sorted selects sorted
files=( ${(@f)$(chezmoi managed --include=files --exclude=externals --path-style relative)} )

for file in $files; do
  abs="$HOME/$file"
  [[ -f $abs ]] || continue
  zstat -A stat +mtime -- "$abs"
  timestamps+=( "${stat[1]} $file" )
done

sorted=( ${(On)timestamps} )

selects=($(
  fzf \
  --multi \
  --height=60% \
  --query=$1 \
  --preview='bat --style=plain --paging=never --color=always --line-range=:200 $HOME/{}' \
  < <(print -r -l -- ${sorted#* })
))

[[ -n $selects ]] || return 1

chezmoi edit $HOME/${^selects}
# }
